#!/bin/bash
# 一键更换 DNS 配置工具
# 功能描述：交互式输入 DNS 地址，自动更新 /etc/resolv.conf
# 默认 DNS：223.5.5.5 (阿里云公共 DNS)
# 注意事项：需要 root 权限执行

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${CYAN}========== 一键更换 DNS 配置 ==========${NC}"
echo ""

# 显示当前 DNS 配置
echo -e "${YELLOW}当前 DNS 配置：${NC}"
if [ -f /etc/resolv.conf ]; then
    grep "^nameserver" /etc/resolv.conf || echo "  (无 nameserver 配置)"
else
    echo "  /etc/resolv.conf 文件不存在"
fi
echo ""

# 读取用户输入的 DNS 地址
read -p "请输入新的 DNS 地址 (直接回车使用默认 223.5.5.5): " INPUT_DNS </dev/tty

# 如果用户没有输入，使用默认值
DNS=${INPUT_DNS:-223.5.5.5}

# 验证 IP 格式（简单验证）
if ! echo "$DNS" | grep -Eq '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'; then
    echo -e "${RED}错误：DNS 地址格式不正确，请输入有效的 IPv4 地址${NC}"
    exit 1
fi

echo ""
echo -e "${YELLOW}准备将 DNS 更改为：${GREEN}$DNS${NC}"

# 检查是否有 root 权限
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}警告：需要 root 权限才能修改 /etc/resolv.conf${NC}"
    echo -e "请使用 ${CYAN}sudo${NC} 或以 root 用户运行此脚本"
    exit 1
fi

# 备份原配置
BACKUP_FILE="/etc/resolv.conf.bak.$(date +%Y%m%d%H%M%S)"
cp /etc/resolv.conf "$BACKUP_FILE" 2>/dev/null
echo -e "${GREEN}✓${NC} 已备份原配置到：$BACKUP_FILE"

# 写入新的 DNS 配置
cat > /etc/resolv.conf << EOF
# Generated by Script Hub DNS Tool
# $(date)
nameserver $DNS
nameserver 8.8.8.8
EOF

# 验证更改
echo ""
echo -e "${GREEN}✅ DNS 配置已更新！${NC}"
echo ""
echo -e "${YELLOW}新的 DNS 配置：${NC}"
cat /etc/resolv.conf
echo ""

# 测试 DNS 解析
echo -e "${YELLOW}测试 DNS 解析...${NC}"
if nslookup baidu.com > /dev/null 2>&1; then
    echo -e "${GREEN}✅ DNS 解析正常！${NC}"
elif ping -c 1 baidu.com > /dev/null 2>&1; then
    echo -e "${GREEN}✅ 网络连通正常！${NC}"
else
    echo -e "${YELLOW}⚠ 无法验证 DNS，请手动检查网络连接${NC}"
fi

echo ""
